alter table public.orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_name text,
  add column if not exists customer_email text,
  add column if not exists customer_phone text,
  add column if not exists customer_document text,
  add column if not exists zip_code text,
  add column if not exists address text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists subtotal numeric(10,2) not null default 0,
  add column if not exists shipping numeric(10,2) not null default 0,
  add column if not exists discount numeric(10,2) not null default 0,
  add column if not exists total numeric(10,2) not null default 0,
  add column if not exists status text not null default 'pending',
  add column if not exists payment_method text,
  add column if not exists payment_provider text default 'mercado_pago',
  add column if not exists payment_provider_order_id text,
  add column if not exists payment_provider_payment_id text,
  add column if not exists paid_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists orders_order_number_idx
  on public.orders (order_number);

alter table public.order_items
  add column if not exists order_id uuid references public.orders(id) on delete cascade,
  add column if not exists product_id text,
  add column if not exists product_name text,
  add column if not exists team text,
  add column if not exists category text,
  add column if not exists season text,
  add column if not exists size text,
  add column if not exists quantity integer not null default 1,
  add column if not exists unit_price numeric(10,2) not null default 0,
  add column if not exists total_price numeric(10,2) not null default 0,
  add column if not exists image text,
  add column if not exists created_at timestamptz not null default now();

alter table public.payments
  add column if not exists order_id uuid references public.orders(id) on delete cascade,
  add column if not exists provider text not null default 'mercado_pago',
  add column if not exists method text,
  add column if not exists status text not null default 'pending',
  add column if not exists provider_payment_id text,
  add column if not exists provider_preference_id text,
  add column if not exists provider_status text,
  add column if not exists provider_status_detail text,
  add column if not exists payment_url text,
  add column if not exists qr_code text,
  add column if not exists qr_code_base64 text,
  add column if not exists barcode text,
  add column if not exists boleto_url text,
  add column if not exists amount numeric(10,2) not null default 0,
  add column if not exists raw_response jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.payment_events
  add column if not exists provider text not null default 'mercado_pago',
  add column if not exists event_type text,
  add column if not exists provider_payment_id text,
  add column if not exists order_id uuid references public.orders(id) on delete set null,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists processed boolean not null default false,
  add column if not exists created_at timestamptz not null default now();

notify pgrst, 'reload schema';
